name: App Serverless CI/CD (AWS SAM)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: ${{ github.repository }} #lo usare para tagear la imagen con el nombre del repo
  AWS_REGION: us-east-1
  STACK_NAME: sam-app

jobs:

  Pre-validations:
    name: Validate & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install aws-sam-cli cfn-lint checkov

      - name: Validate SAM template
        run: sam validate

      - name: Lint CloudFormation
        run: cfn-lint template.yaml

      - name: Security scan (Checkov)
        run: checkov -f template.yaml

      - name: Run tests (placeholder)
        run: |
          echo "Run unit tests here"


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: Pre-validations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Build SAM app
        run: sam build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sam-build
          path: .aws-sam

